### ISSUE TITLE
Field Injection unsafe

### ISSUE THREAD

**Issue by BCantos17** [Ychen192/spring-boot-lambda#3]
https://github.com/Ychen192/spring-boot-lambda/blob/aef6cb9a473cbb55a10e4e66cdd39e7ab2655254/src/main/java/com/yan/springbootlambda/service/TransitService.java#LL23C1-L23C1

Please use constructor injection

**Comment by Ychen192** [comment]
@BCantos17 please have a look at the PR https://github.com/Ychen192/spring-boot-lambda/pull/4
